#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '15.0'
use_frameworks!
## ignore warning
inhibit_all_warnings!
ENV['SWIFT_VERSION'] = '5'

target 'FunLife' do

  pod 'RxSwift'
#
##  pod 'SwiftOCR'
#
  pod 'lottie-ios'

  pod 'HXPhotoPicker'

  pod 'SwiftyJSON'

  pod 'Hero'

  pod 'Kingfisher'

#  pod 'ReactiveCocoa'

  pod 'SnapKit'

  pod 'IQKeyboardManagerSwift'

  pod 'MMKV'

  pod 'RealmSwift'

  pod 'Moya'
##  pod 'Moya/RxSwift'
##  pod 'Moya/ReactiveSwift'
##  pod 'Moya/Combine'
#

  pod 'SwiftDate'
#  
#  pod 'SVGAPlayer'
#

#  pod 'FDFullscreenPopGesture'

#  pod 'TYSnapshotScroll'

  pod 'LookinServer', :configurations => ['Debug']

end

#post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#    end
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
##            if config.name == 'Debug'
##              config.build_settings["VALID_ARCHS"] = "arm64 arm64e x86_64 i386"
##            else
##              config.build_settings["VALID_ARCHS"] = "arm64 arm64e"
##            end
#        end
#    end
#end

